### ISSUE TITLE
Crash in pre-Lollipop devices

### ISSUE THREAD

**Issue by waninkoko** [81813780/AVLoadingIndicatorView#46]
Version 2.0.x is crashing in pre-Lollipop devices because it tries to use a constructor that is only available in API 21 and higher.

The problem is located in this line in AVLoadingIndicatorView:

```java
super(context, attrs, defStyleAttr, defStyleRes);
```

**Comment by 81813780** [comment]
ok , I check it now

**Comment by 81813780** [comment]
Fixed , you can test it in current version 2.0.2

**Comment by 81813780** [comment]
@waninkoko  if works fine in pre-Lollipop , please let me know , and thanks again for your issues .

**Comment by waninkoko** [comment]
@81813780 This issue is fixed but now there is a new one:

```
java.lang.NullPointerException
at com.wang.avi.Indicator.stopAnimators(Indicator.java:109)
at com.wang.avi.Indicator.stop(Indicator.java:126)
at com.wang.avi.AVLoadingIndicatorView.stopAnimation(AVLoadingIndicatorView.java:149)
at com.wang.avi.AVLoadingIndicatorView.onVisibilityChanged(AVLoadingIndicatorView.java:171)
at android.view.View.dispatchVisibilityChanged(View.java:7628)
at android.view.ViewGroup.dispatchVisibilityChanged(ViewGroup.java:1058)
at android.view.ViewGroup.dispatchVisibilityChanged(ViewGroup.java:1058)
at android.view.ViewGroup.dispatchVisibilityChanged(ViewGroup.java:1058)
at android.view.ViewGroup.dispatchVisibilityChanged(ViewGroup.java:1058)
at android.view.View.setFlags(View.java:8632)
at android.view.View.setVisibility(View.java:5830)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2846)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2266)
at android.app.ActivityThread.access$600(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by 81813780** [comment]
Fixed again . I test it fine in Android 4.4.4 with new version 2.0.3

**Comment by waninkoko** [comment]
@81813780 Now it's working great in Android 4.3. Thanks!

**Comment by 81813780** [comment]
@waninkoko :+1:
