### ISSUE TITLE
ClassDefNotFoundException

### ISSUE THREAD

**Issue by blackhawk389** [81813780/AVLoadingIndicatorView#79]
Getting this error on xml preview
`Exception Details java.lang.NoClassDefFoundError: com/wang/avi/R$style   at com.wang.avi.AVLoadingIndicatorView.<init>(AVLoadingIndicatorView.java:76)   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:806)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)   at android.view.LayoutInflater.inflate(LayoutInflater.java:504)   at android.view.LayoutInflater.inflate(LayoutInflater.java:385) Copy stack to clipboard`

**Comment by blackhawk389** [comment]
with 2.X are there any platform constrain, I mean it requires some specific android studio version or build tools or gradle version?
